zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - 2181:2181
kafka:
  image: wurstmeister/kafka
  ports:
    - 9092:9092
  links:
    - zookeeper:zk
  environment:
    BROKER_ID: 1
    KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
    PORT: 9092
    KAFKA_ZOOKEEPER_CONNECT: zk:2181
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock