version: '2'
services:
  zookeeper:
    image: zookeeper:3.4
    ports:
      - 2181:2181
      - 22
  redis:
    image: redis
    ports:
      - 6379:6379
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    links:
      - zookeeper:zk
    environment:
      BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  nimbus:
    image: storm:1.0.3
    command: storm nimbus
    depends_on:
        - zookeeper
    ports:
      - 49773:3773
      - 49772:3772
      - 49627:6627
      - 22
    links: 
      - zookeeper:zk
      - kafka:kafka
      - redis:redis
    volumes:
      - ./mnt-storm:/tmp
  supervisor:
    image: storm:1.0.3
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    ports:
      - 8000
      - 22
    links: 
      - nimbus:nimbus
      - zookeeper:zk
      - kafka:kafka